# 
# Makefile fuer ubasic unter Linux
#
#

CC      = gcc
CFLAGS  = -Wall -g
CFLAGS  += -DUSE_AVR=0
CFLAGS  += -DBREAK_NOT_EXIT=0

OBJ = use-ubasic.o ubasic.o tokenizer.o ubasic_call.o ubasic_cvars.o
BIN = ubasic

ubasic: $(OBJ)
	$(CC) $(CFLAGS) -o $(BIN) $(OBJ) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $<
	
	
.PHONY: clean
clean:
	rm -rf $(BIN) $(OBJ)

